name: Output information 
on: workflow_dispatch 
jobs: 
  info: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Output Github Context 
        run: echo "${{ toJSON(github) }}" ### we are getting metadata , this syntax called as expression, which means we are not outputting plain text. ##context objects 