### WHY CUSTOM ACTIONS -> SIMPLIFY WORKFLOW STEPS >> INSTEAD OF WRITING MULTIPLE STEP DEFINATIONS, WE CAN BUILD AND USE A SINGLE CUSTOM ACTION. 
### MULTIPLE STEPS CAN BE GROUPED INTO A SINGLE CUSTOM ACTION. 
### NO EXISTING COMMUNITY ACTION ->> EXISTING PUBLIC ACTIONS MIGHT NOT SOLVE SPECIFIC PROBLEM WE HAVE IN OUR WORKFLOW. 
### CUSTOM ACTIONS CAN CONTAIN ANY LOGIC YOU NEED TO SOLVE YOUR SPECIFIC WORKFLOW. 
### TYPES OF CUSTOM GHA ->> JS ACTIONS {}, DOCKER ACTIONS, COMPOSITE ACTIONS , OUT OF THEM WE CAN USE ANY OF THE ACTION. 
### JS ACTIONS ->> EXECUTES A JS FILE , USE JS OR ANY PKG LIKE NODEJS. 
### DOCKER ACTIONS ->> CREATING A DOCKERFILE WITH REQUIRED CONFIGURATIONS. 
### COMPOSITE ACTIONS ->> NO PROGRAMMING KNOWLEDGE NEEDED. COMBINE MULTIPLE WORKFLOW STEPS IN ONE SINGLE ACTION. 

name: Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: load and cache deps 
        id: cache-deps 
        uses: ./.github/actions/cached-depsn ### no need to write the action.yml in this and its in root. as it starts at the root level of the proj. 
        with: 
          caching: 'false'
      - name: Output information 
        run: echo "Cache used" ${{ steps.cache-deps.outputs.cache-use }} ## prints the output value for the above custom action step. 
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: load and cache deps 
        uses: ./.github/actions/cached-depsn
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: load and cache deps 
        uses: ./.github/actions/cached-depsn
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."