#### MODULE 6 >>> Using Environment Variables and Secrets ### EV are dynamic like password we keep rotating our passwords to security reasons so we store them in EV. 
#### we can define environment variables under workflow and also can write ev under jobs depends on our needs where to use. 
name: Deployment
on: 
  push: 
    branches: 
      - main 
      - dev 

env: ### we can define ev on just after the workflow 
  MONGO_DB_NAME: gha-demo 
jobs: 
  test: ### we can also define the ev just after the jobs 
    env: 
      MONGODB_CLUSTERADDRESS: 
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }} ### for storing secrets value we can use secrets.----- , just like in the case of env 
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    runs-on: ubuntu-latest
    steps: 
      - name: Get code 
        uses: actions/checkout@v3 
      - name: Cache dependencies 
        uses: actions/cache@v3 
        with: 
          path: ~/.npm 
          key: 
      - name: Install dependencies
        run: npm ci  
      - name: Run Server 
        run:  npm start & npx wait-on localhost 
      - name: Run tests 
        run: npm tests 
      - name: Output Information 
        run: | ### TO GRAB A VALUE WE USE DOUBLE CURLY BRACKETS AND PLACE VALUES HERE. 
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
  deploy: 
    needs: test 
    runs-on: ubuntu-latest 
    steps: 
      - name: Output information  
        run: | ### thats how we store env in the GA 
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODBDB_NAME: ${{ env.MONGODB_NAME }}"  
