### GITHUB ACTION HAS FOUR FUNC WHICH WE CAN USE WITH OUR IF STATEMENTS , FAILURE SUCCESS ALWAYS CANCELLED 
### FAILURE >> RETURNS TRUE WHEN ANY PREV STEP OR JOB FAILED. 
### SUCCESS >> RETURNS TRUE WHEN NONE OF THE PREV STEPS HAVE FAILED. 
### ALWAYS >> CAUSES THE STEPS TO ALWAYS EXECUTE, EVEN WHE N CANCELLED.
### CANCELLED >> RETURNS TRUE IF THE WORKFLOW HAS BEEN CANCELLED. 

name: Using Reusable Workflow  
on: 
  push: 
    branches: 
      - main 

jobs: 
  lint: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Get code 
        uses: actions/checkout@v4 
      - name: Cache dependencies 
        id: cache 
        uses: actions/cache@v4 
        with: 
          path: node_modules 
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies 
        if: steps.cache.outputs.cache-hit != 'true' ### another usecase for if statement 
        run: npm ci 
      - name: Lint code 
        run: npm run lint 

  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Get code 
        uses: actions/checkout@v4 
      - name: Cache dependencies 
        id: cache 
        uses: actions/cache@v4 
        with: 
          path: node_modules 
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies 
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci 
      - name: Test code
        run: npm run test 
      - name: Upload test reports 
        if: failure() && steps.run-tests.outcome == 'failure' ### in this we set the job to execute even the test fails we used these methods from github offi web and without failure && it wont get executed. 
        uses: actions/upload-artifact@v4
        with: 
          name: test-report
          path: test.json 

  build: 
    needs: test 
    runs-on: ubuntu-latest
    steps: 
      - name: Get code 
        uses: actions/checkout@v4 
      - name: Cache dependencies 
        id: cache 
        uses: actions/cache@v4 
        with: 
          path: node_modules 
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies 
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci 
      - name: build-website 
        run: npm run build 
      - name: Upload artifacts 
        uses: actions/upload-artifacts@v4 
        with: ### by providing the input values it got executed otherwise it gives error. 
          artifact-name: dist-files ### passing the required input, this will get executed.   
          path: dist 

  deploy: 
    needs: build 
    uses: . / .github/workflows/reusable.yml ### defines the workflow which we wanna reuse. relative path to the workflow this could be a path to git repo. 
    with: 
      artifacts-name: dist-files
    # secrets: 
    #   some-secrets: ${{ secrets.some-secret }} this is how we could pass the secrets when required. 
  
  deploy-result: 
    needs: deploy 
    runs-on: ubuntu-latest
    steps: 
      - name: Print deploy output 
        run: "${{ needs.deploy.outputs.result }}"
    
  
  report:  #### USING IF STATEMENT ON JOB LEVEL 
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest 
    steps: 
      - name: Output Inormation 
        run: |
          echo "Something went wrong" 
          echo "${{ (github)}}"